### PR TITLE
fix relationships

### LINKED ISSUE #81: Included relationships aren't valid JSONAPI
Postman 2019-04-17 21-44-01

### PR DESCRIPTION
**Pull request by spersico**
closes #81

### CODE REVIEW

File: src/application.ts [hunk 1]
```diff
@@ -9,6 +9,7 @@ import {
 } from "./types";
 import pick from "./utils/pick";
 import unpick from "./utils/unpick";
+import { finished } from "stream";
```
Comment (joelalejandro) [inline src/application.ts]: @spersico This seems to be an unexpected import? I don't see it being used anywhere.

File: src/application.ts [hunk 2]
```diff
@@ -89,14 +90,17 @@ export default class Application {
   async buildOperationResponse(
     data: Resource | Resource[] | void
   ): Promise<OperationResponse> {
-    const included = flatten(await this.extractIncludedResources(data)).filter(
-      Boolean
-    );
+    const included = flatten(await this.extractIncludedResources(data))
+    const uniqueIncluded = Array.from(new Set(included
```
Comment (joelalejandro) [inline src/application.ts]: @spersico This can be written in spread notation:

```ts
const uniqueIncluded = [...new Set(included)].map(...).map(...)
```

File: src/application.ts [hunk 3]
```diff
@@ -89,14 +90,17 @@ export default class Application {
...
+      .map((item: Resource) => `${item.type}_${item.id}`)))
```
Comment (joelalejandro) [inline src/application.ts]: @spersico Shouldn't this be `foreignKeyName`-aware?

File: src/application.ts [hunk 4]
```diff
@@ -150,20 +156,19 @@ export default class Application {
...
     Object.keys(data.relationships).forEach(relationshipName => {
       if (Array.isArray(data.relationships[relationshipName])) {
-        data.relationships[relationshipName] = (data.relationships[
-          relationshipName
-        ] as any).map(rel => {
-          rel["type"] = schemaRelationships[relationshipName].type().type;
-          return rel;
-        });
+        data.relationships[relationshipName] =
+          (data.relationships[relationshipName] as any).map(rel => {
```
Comment (joelalejandro) [inline src/application.ts]: @spersico Can you add a `// TODO` here so we can take care of this `any` later? (It's probably mine, but just so I don't forget about it.)

File: src/application.ts [hunk 5]
```diff
@@ -200,5 +205,10 @@ export default class Application {
         });
       })
     );
+    const validIncluded = flatten(rawInclude.filter(Boolean));
```
Comment (joelalejandro) [inline src/application.ts]: @spersico This seems a repetition from `Application#buildOperationResponse`'s first three lines. Should we extract into a single, shared function?

File: src/application.ts (hunk 4 above)
Comment (spersico) [reply src/application.ts]: will do

File: src/application.ts (hunk 5 above)
Comment (spersico) [reply src/application.ts]: noup, I'm a dumbass, I just forgot to delete the other one

File: src/application.ts (hunk 3 above)
Comment (spersico) [reply src/application.ts]: @joelalejandro what do you mean by foreignKeyName?
I check only for repeated resources, I assume that the id and type are unique for each resource, and that's what I use, unless there's something that I'm not seeing

File: src/application.ts (hunk 2 above)
Comment (spersico) [reply src/application.ts]: done
